### ISSUE TITLE
help needed 

### ISSUE THREAD

**Issue by rahmanshaber** [AIIX/Mycroft-Ai-QtApplication#10]
i am in linux 4.14 manjaro , xfce

i tried to run the app image but it dose not run and shows this
` ./MycroftQt.AppImage
./MycroftQt.AppImage: symbol lookup error: /usr/lib/libfontconfig.so.1: undefined symbol: FT_Done_MM_Var
`

also build from qmake , it runs and opens but  shows error 
![i](https://user-images.githubusercontent.com/30831735/42364932-bac78f00-811e-11e8-9b2d-bbb3e3b2811c.png)

DO MYCROFT NEED A ACTIVE INTERNET CONNECTION??

how to run the appimage.did not understand 
`Download -> chmod +x mycroft-qtapplication.AppImage -> Run`

also did not understand what you mean by
`Go To Settings and Set the Start and Stop path to your Mycroft.sh file in the Mycroft-Core folder`

THANKS

**Comment by rahmanshaber** [comment]
waiting

**Comment by BenjaminHCCarr** [comment]
This is a mycroft front end. This is an instance of mycroft. You need to point it an a docker/RPi/Linux instance that is running the mycroft server.

**Comment by rahmanshaber** [comment]
i don't know how to do that

**Comment by KathyReid** [comment]
Hi @rahmanshaber, please install Mycroft for Linux first. Then you can point the QT app at the Mycroft instance. 

https://mycroft.ai/documentation/linux

If you need support, join us in https://chat.mycroft.ai

**Comment by AIIX** [comment]
Hi @rahmanshaber, follow the guide above and install Mycroft-core via git, and then press the start button.. or else look in the settings and point the path to ./start-mycroft.sh

**Comment by rahmanshaber** [comment]
installing mycroft-core by compiling is can't be done by my pc.my pc is old hardware.
i told the mycroft team to build a snap package for it and they tried but failed in past.they reopen a issue to asking for help in packaging as Snap and Flatpack .
if your are interested and help them this app and mycroft will be a great app.
[Support snap packages](https://github.com/MycroftAI/mycroft-core/issues/246) and [Package as Snap or Flatpak](https://github.com/MycroftAI/mycroft-core/issues/1723)

thanks.
