### ISSUE TITLE
Dont't host large binaries in git repository

### ISSUE THREAD

**Issue by probonopd** [AIIX/Mycroft-Ai-QtApplication#3]
Please consider using GitHub Releases for hosting large binaries such as the AppImage. GitHub doesn't like it when large binaries are stored in Git repositories. 

Something like https://github.com/probonopd/uploadtool can be used to automate the uploading.

**Comment by AIIX** [comment]
New Appimage posted as release, have not used the uploadtool did a manual release this time around.
