### ISSUE TITLE
Can't run on Ubuntu due to missing dependency libicui18n.so.57

### ISSUE THREAD

**Issue by chrison999** [AIIX/Mycroft-Ai-QtApplication#5]
Trying to run the Appimage on Ubuntu 16.04LTS but keep running up against this error:

`Desktop/mycroft-qtapplication.AppImage: error while loading shared libraries: libicui18n.so.57: cannot open shared object file: No such file or directory`

I have googled looking for this library for ubuntu but can only find RPM versions for Fedora.  There _is_ libicu55 available for Ubuntu.  Can you use version 55 instead of 57 when compiling the Appimage so that it runs on Ubuntu?

**Comment by AIIX** [comment]
fixed on new release.
